# Generated by Django 5.2.6 on 2025-09-19 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0002_driverprofile_is_verified_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bus_number", models.CharField(max_length=20, unique=True)),
                ("license_plate", models.CharField(max_length=15, unique=True)),
                (
                    "bus_type",
                    models.CharField(
                        choices=[
                            ("standard", "Standard"),
                            ("deluxe", "Deluxe"),
                            ("ac", "Air Conditioned"),
                        ],
                        default="standard",
                        max_length=10,
                    ),
                ),
                ("total_seats", models.IntegerField(default=30)),
                (
                    "capacity",
                    models.IntegerField(help_text="Maximum passenger capacity"),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="BusStop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("address", models.TextField(blank=True)),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "total_distance",
                    models.FloatField(default=0, help_text="Distance in kilometers"),
                ),
                (
                    "estimated_duration",
                    models.IntegerField(
                        default=0, help_text="Estimated duration in minutes"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="BusRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "bus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bus_routes",
                        to="tracking.bus",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.driverprofile",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bus_routes",
                        to="tracking.route",
                    ),
                ),
            ],
            options={
                "unique_together": {("bus", "route", "start_time")},
            },
        ),
        migrations.CreateModel(
            name="RouteStop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sequence",
                    models.IntegerField(help_text="Order of stops in the route"),
                ),
                (
                    "distance_from_previous",
                    models.FloatField(
                        default=0, help_text="Distance from previous stop in km"
                    ),
                ),
                (
                    "estimated_time_from_previous",
                    models.IntegerField(
                        default=0, help_text="Time from previous stop in minutes"
                    ),
                ),
                (
                    "bus_stop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tracking.busstop",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="route_stops",
                        to="tracking.route",
                    ),
                ),
            ],
            options={
                "ordering": ["route", "sequence"],
                "unique_together": {("route", "sequence")},
            },
        ),
        migrations.CreateModel(
            name="Seat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seat_number", models.CharField(max_length=10)),
                ("is_available", models.BooleanField(default=True)),
                (
                    "bus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seats",
                        to="tracking.bus",
                    ),
                ),
            ],
            options={
                "unique_together": {("bus", "seat_number")},
            },
        ),
    ]
